### ISSUE TITLE
Crawl Error

### ISSUE THREAD

**Issue by garyanewsome** [ninjapanzer/savvyshots_rails#101]
<img width="693" alt="screen shot 2017-06-14 at 8 14 23 am" src="https://user-images.githubusercontent.com/13909325/27131644-8d7ded58-50d9-11e7-988c-19c3a238727e.png">

**Comment by ninjapanzer** [comment]
<img width="536" alt="screen shot 2017-06-15 at 10 26 18 am" src="https://user-images.githubusercontent.com/159591/27186012-18ca4786-51b5-11e7-8a27-2d35429c0d59.png">
The footers "Contact via Web" link has a relative path

**Comment by garyanewsome** [comment]
Link works in production and in dev
